In [1]:
import numpy as np

### Broadcasting


In [2]:
x = np.array([1,2,3,4])
print(x)
print(x+4)

[1 2 3 4]
[5 6 7 8]


In [3]:
X = np.array([[10,20,30,40],[40,50,60,70]])
print(X)
print(X+x)

[[10 20 30 40]
 [40 50 60 70]]
[[11 22 33 44]
 [41 52 63 74]]


### Element wise multiplication: Hadamard Product

In [4]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[0,2],
              [3,2]])

A*B

array([[0, 4],
       [9, 8]])

### Matrix Multiplication

In [5]:
np.dot(A,B)

array([[ 6,  6],
       [12, 14]])