In [1]:
import numpy as np

### Norm

In [2]:
x = np.array([3,4])

lp2 = np.linalg.norm(x)
print(lp2)

5.0


In [4]:
lp1 = np.linalg.norm(x,ord = 1)
print(lp1)

7.0


In [5]:
lpinf = np.linalg.norm(x,ord = np.inf)
print(lpinf)

4.0


### Determinant

In [7]:
A = np.array([[1,2],
             [3,4]])
print(np.linalg.det(A))

-2.0000000000000004


### Inverse

In [10]:
Ainv = np.linalg.inv(A)
# print(Ainv)
print(np.dot(A,Ainv))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [13]:
B = np.array([[6,8],
             [3,4]])

pinv = np.linalg.pinv(B)
print(pinv)

[[0.048 0.024]
 [0.064 0.032]]


>When matrix is invertible, pseudo inverse is equal to the inverse of the matrix. Pseudo inverse can also be defined for non-invertible matrices

In [14]:
print(np.dot(B,pinv))

[[0.8 0.4]
 [0.4 0.2]]


### Solve a system of equations

In [15]:
a = np.array([[2,3],[3,1]])
b = np.array([8,5])

In [16]:
np.linalg.solve(a,b)

array([1., 2.])